#!/usr/bin/env bash

wget http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-linux-ia32.tar.gz -P ./ubin
cd ./ubin
tar -vxzf nwjs*
cd nwjs*
sudo rm -rf /usr/local/bin/nw
sudo ln -s $(pwd)/nw /usr/local/bin/nw
cd ../..
