#!/usr/bin/env bash

mv ../nwjs ../nwjs.bak
wget http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-linux-ia32.tar.gz -P ..
rm -rf ../nwjs.bak
cd .. 
tar -vxzf nwjs-*
rm -rf nwjs-*.tar.gz
mv nwjs-* nwjs
cd nwjs
sudo rm -rf /usr/local/bin/nw
sudo ln -s $(pwd)/nw /usr/local/bin/nw
cd ../dmi
