#!/usr/bin/env bash

wget http://www.sqlite.org/2015/sqlite-autoconf-3090200.tar.gz -P ..
cd .. 
tar -vxzf sqlite-autoconf*
rm -rf sqlite-autoconf*.tar.gz
cd sqlite-autoconf*
./configure
make
sudo make install
cd ..
rm -rf sqlite-autoconf*
cd dmi
