#!/usr/bin/env bash

git clone https://github.com/ariya/phantomjs.git ../phantomjs
cd ../phantomjs
sudo apt-get install build-essential g++ flex bison gperf ruby perl libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev libjpeg-dev python libx11-dev libxext-dev
./build.sh
sudo cp ./bin/phantomjs /usr/local/bin
cd ..
rm -rf phantomjs
cd dmi
